# This is a templated file and must be kept up-to-date with the original
# from upstream at https://github.com/canonical/se-tooling-ci-common.
name: Publish to ghcr.io

on:
  workflow_run:
    workflows: [Python Package]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: image

jobs:
  build:
    # Include the build workflow.
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iduses
    uses: ./.github/workflows/build.yaml

  ghcr-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get packages
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: processor_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.IMAGE_TAG }}

      - name: Build and publish Docker
        id: processor-build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.processor_meta.outputs.tags }}
          labels: ${{ steps.processor_meta.outputs.labels }}
