name: Docker publish (ghcr.io)

on:
  schedule:
    - cron: '38 11 * * *'
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ['v*.*.*']
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18"

      - name: Test and Build
        run: make all

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # NEED FOLLOWING BLOCK FOR EACH IMAGE
      - name: Extract Docker metadata - <IMAGE_NAME_GOES_HERE>
        id: processor_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/<IMAGE_NAME_GOES_HERE>

      - name: Build and publish Docker - <IMAGE_NAME_GOES_HERE>
        id: processor-build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: <PATH TO DOCKERFILE>
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.processor_meta.outputs.tags }}
          labels: ${{ steps.processor_meta.outputs.labels }}

